'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function newId(prefix) {
  return `${prefix}_${crypto.randomUUID()}`;
}

function createStore(filePath) {
  let data = null;

  function load() {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    if (fs.existsSync(filePath)) {
      const raw = fs.readFileSync(filePath, 'utf8');
      try {
        data = JSON.parse(raw);
      } catch (err) {
        throw new Error(`ledger.json is corrupted and could not be parsed: ${err.message}`);
      }
    } else {
      data = { customers: [], invoices: [], ledgerEntries: [], invoiceCounter: 0 };
      save();
    }
  }

  function save() {
    const tmp = `${filePath}.tmp`;
    fs.writeFileSync(tmp, JSON.stringify(data, null, 2));
    fs.renameSync(tmp, filePath);
  }

  function ensureLoaded() {
    if (!data) load();
  }

  function init() {
    ensureLoaded();
  }

  function computeBalance(customerId) {
    let balance = 0;
    for (const e of data.ledgerEntries) {
      if (e.customerId !== customerId) continue;
      balance += e.type === 'due' ? e.amount : -e.amount;
    }
    return balance;
  }

  function listCustomers() {
    ensureLoaded();
    return data.customers.map((c) => ({ ...c, balance: computeBalance(c.id) }));
  }

  function getCustomer(id) {
    ensureLoaded();
    const c = data.customers.find((c) => c.id === id);
    if (!c) throw new Error('Customer not found');
    return { ...c, balance: computeBalance(id) };
  }

  function addCustomer({ name, phone }) {
    ensureLoaded();
    const trimmedName = (name || '').trim();
    if (!trimmedName) throw new Error('Customer name is required');
    const trimmedPhone = (phone || '').trim();
    if (!trimmedPhone) throw new Error('Phone number is required');
    if (!/^\d+$/.test(trimmedPhone)) throw new Error('Phone number must contain digits only');
    const cust = { id: newId('cust'), name: trimmedName, phone: trimmedPhone, createdAt: new Date().toISOString() };
    data.customers.push(cust);
    save();
    return { ...cust, balance: 0 };
  }

  function listEntries(customerId) {
    ensureLoaded();
    if (!data.customers.some((c) => c.id === customerId)) throw new Error('Customer not found');
    // ledgerEntries is always appended in chronological order — filtering
    // preserves that order, so this is already oldest-first with no sort
    // needed (same lesson as stockStore's movement-order fix: don't sort by
    // millisecond timestamps when array order already encodes the truth).
    return data.ledgerEntries.filter((e) => e.customerId === customerId);
  }

  function addManualEntry(customerId, type, amount, reason, note) {
    ensureLoaded();
    if (!data.customers.some((c) => c.id === customerId)) throw new Error('Customer not found');
    const n = Number(amount);
    if (!Number.isFinite(n) || n <= 0) throw new Error('Amount must be a positive number');
    const entry = { id: newId('le'), customerId, type, amount: n, reason, invoiceId: null, note: note || '', at: new Date().toISOString() };
    data.ledgerEntries.push(entry);
    save();
    return entry;
  }

  function addOldBalance(customerId, amount, note) {
    return addManualEntry(customerId, 'due', amount, 'old-balance', note);
  }

  function addCashPaid(customerId, amount, note) {
    return addManualEntry(customerId, 'payment', amount, 'cash-paid', note);
  }

  // Invoice and advance entries are generated by createInvoice and stay
  // paired with an actual invoice record (and, for invoices, already-deducted
  // stock) — EDITING them here would desync the ledger balance from what the
  // printed/WhatsApped invoice already says (the PDF can't retroactively
  // change), so amount/note edits stay restricted to the manually-added
  // types (old-balance, cash-paid). DELETING is a separate, broader
  // capability — see findDeletableEntry below — since fully voiding a
  // mistaken invoice is a real, explicitly-requested operator need, unlike
  // editing one in place.
  function findEditableEntry(entryId) {
    const entry = data.ledgerEntries.find((e) => e.id === entryId);
    if (!entry) throw new Error('Ledger entry not found');
    if (entry.reason !== 'old-balance' && entry.reason !== 'cash-paid') {
      throw new Error('Only manually-added entries (Old Balance, Cash Paid) can be edited');
    }
    return entry;
  }

  function findDeletableEntry(entryId) {
    const entry = data.ledgerEntries.find((e) => e.id === entryId);
    if (!entry) throw new Error('Ledger entry not found');
    return entry;
  }

  function updateEntry(entryId, { amount, note } = {}) {
    ensureLoaded();
    const entry = findEditableEntry(entryId);
    if (amount !== undefined) {
      const n = Number(amount);
      if (!Number.isFinite(n) || n <= 0) throw new Error('Amount must be a positive number');
      entry.amount = n;
    }
    if (note !== undefined) entry.note = note || '';
    save();
    return entry;
  }

  // Deleting an 'invoice' entry voids the whole invoice: the invoice record
  // itself and any paired 'advance' entry (which only ever exists because of
  // that invoice) are removed together, so nothing dangling is left behind —
  // e.g. invoice.html?id=X would otherwise still resolve after the ledger
  // entry that referenced it was gone. Deleting a standalone 'advance' entry
  // (without touching the invoice) is also allowed — that's just correcting
  // a mis-recorded advance amount independent of the invoice existing.
  // This deliberately does NOT touch stock — any stock already deducted for
  // a voided invoice is not reversed here (the item may have since been
  // renamed, recategorized, or deleted, so an automatic reversal risks
  // silently corrupting current inventory); correct stock manually via the
  // Stock page's Adjust action if needed.
  function deleteEntry(entryId) {
    ensureLoaded();
    const entry = findDeletableEntry(entryId);
    const idsToRemove = new Set([entryId]);
    if (entry.reason === 'invoice' && entry.invoiceId) {
      data.invoices = data.invoices.filter((inv) => inv.id !== entry.invoiceId);
      data.ledgerEntries
        .filter((e) => e.invoiceId === entry.invoiceId)
        .forEach((e) => idsToRemove.add(e.id));
    }
    data.ledgerEntries = data.ledgerEntries.filter((e) => !idsToRemove.has(e.id));
    save();
  }

  // Cascades: removes the customer plus every ledger entry and invoice
  // record tied to them. Like deleteEntry, this never touches stock.
  function deleteCustomer(customerId) {
    ensureLoaded();
    const idx = data.customers.findIndex((c) => c.id === customerId);
    if (idx === -1) throw new Error('Customer not found');
    data.customers.splice(idx, 1);
    data.invoices = data.invoices.filter((inv) => inv.customerId !== customerId);
    data.ledgerEntries = data.ledgerEntries.filter((e) => e.customerId !== customerId);
    save();
  }

  // Nuclear option: wipes every customer, invoice, and ledger entry, and
  // resets invoice numbering back to 0. Guarded at the route level by a
  // required exact confirmation phrase (not just a DELETE verb) — this is
  // meant to be very hard to trigger by accident.
  function resetAll() {
    ensureLoaded();
    data.customers = [];
    data.invoices = [];
    data.ledgerEntries = [];
    data.invoiceCounter = 0;
    save();
  }

  function getInvoice(id) {
    ensureLoaded();
    const inv = data.invoices.find((i) => i.id === id);
    if (!inv) throw new Error('Invoice not found');
    return inv;
  }

  function createInvoice({ customerId, date, mobile, lorry, items, sub, lab, weigh, freight, unload, gst, others, oldbal, advance }) {
    ensureLoaded();
    if (!customerId || !data.customers.some((c) => c.id === customerId)) throw new Error('Customer not found');
    if (!Array.isArray(items) || !items.length) throw new Error('Items are required');
    const n = (v) => Number(v) || 0;
    const total = n(sub) + n(lab) + n(weigh) + n(freight) + n(unload) + n(gst) + n(others);
    data.invoiceCounter = (data.invoiceCounter || 0) + 1;
    // oldbal/advance are stored for display/PDF fidelity only (they mirror
    // what was printed on the physical slip) — they never factor into
    // `total`, which stays sub+lab+weigh+freight+unload+gst+others so the
    // ledger due amount can never double-count a pre-existing balance.
    const invoice = {
      id: newId('inv'),
      invoiceNo: data.invoiceCounter,
      customerId,
      date: date || '',
      mobile: mobile || '',
      lorry: lorry || '',
      items,
      sub: n(sub), lab: n(lab), weigh: n(weigh), freight: n(freight), unload: n(unload), gst: n(gst), others: n(others),
      oldbal: n(oldbal), advance: n(advance),
      total,
      createdAt: new Date().toISOString(),
    };
    data.invoices.push(invoice);
    data.ledgerEntries.push({ id: newId('le'), customerId, type: 'due', amount: total, reason: 'invoice', invoiceId: invoice.id, note: '', at: new Date().toISOString() });
    const advanceAmt = n(advance);
    if (advanceAmt > 0) {
      data.ledgerEntries.push({ id: newId('le'), customerId, type: 'payment', amount: advanceAmt, reason: 'advance', invoiceId: invoice.id, note: '', at: new Date().toISOString() });
    }
    save();
    return invoice;
  }

  return {
    init,
    listCustomers,
    getCustomer,
    addCustomer,
    deleteCustomer,
    listEntries,
    addOldBalance,
    addCashPaid,
    updateEntry,
    deleteEntry,
    getInvoice,
    createInvoice,
    resetAll,
  };
}

module.exports = { createStore };
